name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        run: echo "Checkstyle plugin will run automatically in Maven validate phase"

      - name: Run Checkstyle
        run: mvn -q -DskipTests=true validate

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
          with:
            name: checkstyle.xml
            path: target/checkstyle.xml
            if-no-files-found: warn

      - name: Run Maven Test
        run: mvn -q test

      - name: Jacoco Report
        uses: actions/upload-artifact@v4
          with:
            name: jacoco.xml
            path: target/site/jacoco/jacoco.xml
            if-no-files-found: warn